Added link on item show to parent batch
DeepBlueCLtd/RCO pull request #222
Opened 2023-05-01 10:15 UTC by TahaKhanAbdalli

Fixes #213

2023-05-01 10:28 UTC, IanMayo requested changes
For the `Batch`, we need to show the `BatchNumber`, rather than `name`:
![image](https://user-images.githubusercontent.com/1108513/235440798-a06a5f50-08d9-470d-a03f-e6b09bd9655e.png)


Hmm, we should also have a `Batch:` label next to it.

2023-05-01 10:59 UTC, IanMayo commented
`batch` link currently goes to `BatchEdit`. Could it go to `BatchShow` please?

2023-05-02 07:50 UTC, TahaKhanAbdalli commented
updated.

2023-05-02 08:27 UTC, IanMayo approved these changes

2023-05-02 08:51 UTC, merged