285 history button
DeepBlueCLtd/RCO pull request #329
Opened 2023-05-24 10:57 UTC by TahaKhanAbdalli

Fixes #285

2023-05-26 06:51 UTC, IanMayo commented
(I've lost this message, so re-typing)

Could we also have the `history` button for `Users` and all of the `Reference Data` resources, please?

2023-05-30 05:43 UTC, IanMayo commented
Thanks @TahaKhanAbdalli - but could you solve these issues please?

(I know it's just the linter, and the code works fine, but I'd like to keep us at zero linter issues ;-) )
<img width="833" alt="image" src="https://github.com/DeepBlueCLtd/RCO/assets/1108513/2a9d81aa-0432-4da8-bbaf-0c824db1a4eb">

2023-06-01 09:21 UTC, IanMayo requested changes
I've just logged in as `ian` in dev-tools I can see that the audit item has been created. But, when I click `History` for the user `ian` it is empty.  This looks like a bug.

2023-06-01 09:28 UTC, TahaKhanAbdalli commented
The `login` and `logout` actions do not have any `resource` attached to them, therefore the `history` shows empty. But if you depart user or do any actions whose `target resource` is users, then it will show in the history page with items listed.

2023-06-01 09:32 UTC, IanMayo commented
Sure. The history for `UserShow` is a special case. It shows edits to that resource.  It should also include data changes conducted by that resource (including login, loan, edit).

This will let us view/review all of the interactions for that RCO user.

2023-06-01 12:20 UTC, IanMayo commented
Hello @TahaKhanAbdalli - is it possible to show user events that _either_ record changes to the details for this user, _or_ changes performed by this user, _or_ activities that relate to this user (items loaned to them).

2023-06-02 09:19 UTC, IanMayo commented on src/resources/vault-locations/VaultLocationList.tsx
Hello @TahaKhanAbdalli  - I've tried calling the `setOpen` state entity directly from the TSX.

It simplifies the code, but is it ok to do that?

2023-06-02 10:39 UTC, IanMayo approved these changes

2023-06-02 10:44 UTC, merged